name: Flutter GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.6
          cache: true

      # Install Melos
      - name: Install Melos
        run: dart pub global activate melos

      # Bootstrap Melos
      - name: Bootstrap Melos
        run: melos bootstrap
      
      # Analyze
      - name: Analyze
        run: melos analyze